name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  PACKAGE_NAME: basepak
  OWNER: tomaDev

jobs:
  check_pypi:
    runs-on: ubuntu-latest
    outputs:
      PYPI_VERSION: ${{ steps.get.outputs.PYPI_VERSION }}
    steps:
      - name: Fetch information from PyPI
        id: get
        run: |
          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
          version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
          if [ -z "$version" ]; then
            echo "Package not found on PyPI."
            version="0.0.0"
          fi
          echo "Latest version on PyPI: $version"
          echo "PYPI_VERSION=$version" >> $GITHUB_OUTPUT

  setup_and_build:
    needs: [check_pypi]
    name: project setup and build
    runs-on: ubuntu-latest
    outputs:
      NEW_VERSION: ${{ steps.get.outputs.NEW_VERSION }}
    steps:
      - name: Get the new project version
        id: get
        run: echo "NEW_VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Compare versions and exit if not newer
        run: |
          PYPI_VERSION=${{ needs.check_pypi.outputs.PYPI_VERSION }}
          NEW_VERSION=${{ steps.get.outputs.NEW_VERSION }}
          echo "New release version - $NEW_VERSION"
          echo "latest PyPI version - $PYPI_VERSION"
          if [ "$NEW_VERSION" == "$PYPI_VERSION" ]; then
            echo "same version. No need to release"
            exit 1
          elif [ "$(printf '%s\n' "$PYPI_VERSION" "$NEW_VERSION" | sort -rbV | head -n 1)" != "$NEW_VERSION" ]; then
            echo "The new version $NEW_VERSION is not greater than the latest version $PYPI_VERSION on PyPI"
            exit 1
          else
            echo "The new version $NEW_VERSION is greater than the latest version $PYPI_VERSION on PyPI"
          fi

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.6.0"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Validate package version matches tag version
        run: |
          PACKAGE_VERSION="$(python -c 'import src.basepak as v;print(v.__version__)')"
          TAG_VERSION="${{ steps.get.outputs.NEW_VERSION }}"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
              echo "Version mismatch: (package internal) $PACKAGE_VERSION != $TAG_VERSION (tag)"
              exit 1
          fi

      - name: Install the project
        run: uv sync --all-extras --frozen --no-editable

      - name: Build the project
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  github_release:
    name: Create GitHub Release
    needs: [setup_and_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=v${{ needs.setup_and_build.outputs.NEW_VERSION }}
          gh release create $VERSION dist/* --title $VERSION --generate-notes

  pypi_publish:
    name: Upload release to PyPI
    needs: [setup_and_build]
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
